Web2.2/Models/CalcModel.cs
using Web2._2.Services;

namespace Web2._2.Models
{
    public class CalcModel
    {
        public int a { get; set; }
        public int b { get; set; }
        public Operation? Operation { get; set; }
        public string? GetValue() { return CalcService.DoCalculation(a,b,Operation); }
    }
}

Web2.2/Controllers/CalcController.cs
using Microsoft.AspNetCore.Mvc;
using Web2._2.Models;
using Web2._2.Services;

namespace Web2._2.Controllers
{
    public class CalcController : Controller
    {
        public IActionResult Manual()
        {
            ViewData["Title"] = "Manual";

            if (Request.Method == "POST")
            {
                _ = int.TryParse(HttpContext.Request.Form["a"], out int a);
                _ = int.TryParse(HttpContext.Request.Form["b"], out int b);
                _ = int.TryParse(HttpContext.Request.Form["operation"], out int op);

                ViewData["Result"] = CalcService.DoCalculation(a, b, (Operation)op);
            }

            return View("MainForm");
        }

        [HttpGet]
        public IActionResult ManualWithSeparateHandlers()
        {
            ViewData["Title"] = "ManualWithSeparateHandlers";
            return View("MainForm");
        }

        [HttpPost]
        public IActionResult ManualWithSeparateHandlers(int? __)
        {
            ViewData["Title"] = "ManualWithSeparateHandlers";

            _ = int.TryParse(HttpContext.Request.Form["a"], out int a);
            _ = int.TryParse(HttpContext.Request.Form["b"], out int b);
            _ = int.TryParse(HttpContext.Request.Form["operation"], out int op);

            ViewData["Result"] = CalcService.DoCalculation(a, b, (Operation)op);

            return View("MainForm");
        }

        public IActionResult ModelBindingInParameters(int a, int b, Operation? operation)
        {
            ViewData["Title"] = "ModelBindingInParameters";
            ViewData["Result"] = CalcService.DoCalculation(a, b, operation);
            return View("MainForm");
        }

        public IActionResult ModelBindingInSeparateModel(CalcModel calcModel)
        {
            ViewData["Title"] = "ModelBindingInSeparateModel";
            ViewData["Result"] = calcModel.GetValue();
            return View("MainForm");
        }
    }
}

Web2.2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Web2._2.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Web2.2/Views/Calc/MainForm.cshtml
@using Web2._2.Services

@{
    if (ViewData["Result"] == null)
    {
        <div class="text-left">
            <h1 class="display-4">@ViewData["Title"]</h1>
            @using (Html.BeginForm())
            {
                @Html.TextBox("a","", new { type="number" })
                @Html.DropDownList("operation", Html.GetEnumSelectList(typeof(Operation)))
                @Html.TextBox("b","", new { type="number" })
                <input type="submit" value="Submit" />
            }
        </div>
    }
    else
    {
        <div class="text-left">
            <h1 class="display-4">Result</h1>
            <p>@ViewData["Result"]</p>
        </div>
    }
}

Web2.2/Views/Home/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-left">
    <h1 class="display-4">Form parameters parsing demo</h1>
    <ul>
        <li><a asp-controller="Calc" asp-action="Manual">Manual parsing in single action</a></li>
        <li><a asp-controller="Calc" asp-action="ManualWithSeparateHandlers">Manual parsing in separate action</a></li>
        <li><a asp-controller="Calc" asp-action="ModelBindingInParameters">Model binding (parameters)</a></li>
        <li><a asp-controller="Calc" asp-action="ModelBindingInSeparateModel">Model binding (separate model)</a></li>
    </ul>
</div>

Web2.2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web2.2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web2._2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web2.2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>